### ISSUE TITLE
Connect DimLevel gui to RoomControl Server - STEP 1

### ISSUE THREAD

**Issue by KristefC** [MinboChung/leshan_assignment#11]
Step 1: Method to Update new Dim Levels

Handles receiving a new peak power value from the Demand Response GUI to the RoomControl Server.
It calculates the new dim level based on this value and sends the updated dim level to each registered luminaire.

// insert the code inside public class RoomControl

**Code:**

        private static Map<String, Integer> luminairesPeakPower = new HashMap<>();
	private static int maxPeakRoomPower;

	//new total allowed peak power is set via GUI
	public static void handleNewTotalAllowedPeakPower(int totalAllowedPeakPower){
		double newDimLevel =(double)totalAllowedPeakPower/maxPeakRoomPower*100;
		newDimLevel =Math.min(newDimLevel, 100); //set the dimlevel to max 100
		System.out.println("Calculated new dim level: " +newDimLevel+"%");
		updatePostLuminairesDimLevel(newDimLevel);
	}

**Comment by MinboChung** [comment]
Please reference this sequence diagram :)

![Image](https://github.com/user-attachments/assets/7024ee08-ccb8-47b2-94f0-5a02a55edad1)

**Comment by MinboChung** [comment]
![Image](https://github.com/user-attachments/assets/81e33f36-02d4-480d-b0ce-38613ffc7dae)

The yellow circled
