### ISSUE TITLE
Confirm if only applies to LED when we trigger button on presence detector

### ISSUE THREAD

**Issue by KristefC** [MinboChung/leshan_assignment#22]

**Comment by KristefC** [comment]
![Image](https://github.com/user-attachments/assets/321214c6-aa1e-4e21-9444-5f42a732c0c8)
<img width="647" alt="Image" src="https://github.com/user-attachments/assets/59bc16ac-4346-4ad2-8035-5f44aa2dd6a5" />

The concern is that the sequence only applies to LED.

**Comment by MinboChung** [comment]
Only applies to LED. The purpose of having types was to deregister unknown types.
